config/routes.rb
Rails.application.routes.draw do


  root to: "locales#redirect_on_locale"

  devise_for :users, skip: [:password, :registration, :confirmation, :invitations], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
    post "/users/invitation" => "devise/invitations#create", as: :user_invitation
    put "/users/invitation" => "devise/invitations#update", as: nil
    patch "/users/invitation" => "devise/invitations#update", as: nil
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  localized do

    root to: "home#index"

    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #devise_for :users, controllers: {
    #      registrations: 'registrations',
    #      omniauth_callbacks: "callbacks"
    #    }

    match 'users/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
    devise_for :users, skip: [:omniauth_callbacks], controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords', invitations: 'invitations' }

    as :user do
      get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
      post "/users/invitation" => "devise/invitations#create", as: :user_invitation
      put "/users/invitation" => "devise/invitations#update", as: nil
      patch "/users/invitation" => "devise/invitations#update", as: nil
    end

    resources :knowledgebase, :as => 'categories', :controller => "categories", except: [:new, :edit, :create, :update] do
      resources :docs, except: [:new, :edit, :create, :update]
    end

    resources :docs, except: [:new, :edit] do
      resources :comments, only: :create
    end
    resources :community, :as => 'forums', :controller => "forums" do
      resources :topics
    end
    resources :topics do
      resources :posts
    end
    resources :posts do
      resources :flags, only: [:create]
    end

    post 'topic/:id/vote' => 'topics#up_vote', as: :up_vote, defaults: { format: 'js' }
    post 'post/:id/vote' => 'posts#up_vote', as: :post_vote, defaults: { format: 'js' }
    get 'thanks' => 'topics#thanks', as: :topic_thanks
    get 'result' => 'result#index', as: :result
    get 'search' => 'result#search', as: :search
    get 'tickets' => 'topics#tickets', as: :tickets
    get 'ticket/:id/' => 'topics#ticket', as: :ticket
    get 'locales/select' => 'locales#select', as: :select_locale
  end

  get '/switch_locale' => 'home#switch_locale', as: :switch_locale

  # Widget Routes
  get 'widget' => 'widget/topics#new', as: :widget
  namespace :widget do
    get 'index' => 'topics#new', as: :widget
    post 'topics' => 'topics#create', as: :create
    get 'topics/thanks' => 'topics#thanks', as: :thanks
  end

  # Webhook Routes
  namespace :webhook do
    post 'form/:token' => 'inbound#form', as: :form
  end

  # Admin Routes

  namespace :admin do

    # Extra topic Routes
    get 'topics/update_topic' => 'topics#update_topic', as: :update_topic, defaults: {format: 'js'}
    post 'topics/merge_tickets' => 'topics#merge_tickets', as: :merge_tickets
    patch 'topics/update_tags' => 'topics#update_tags', as: :update_topic_tags
    get 'topics/update_multiple' => 'topics#update_multiple_tickets', as: :update_multiple_tickets
    get 'topics/assign_agent' => 'topics#assign_agent', as: :assign_agent
    get 'topics/unassign_agent' => 'topics#unassign_agent', as: :unassign_agent
    get 'topics/toggle_privacy' => 'topics#toggle_privacy', as: :toggle_privacy
    get 'topics/:id/toggle' => 'topics#toggle_post', as: :toggle_post
    get 'topics/assign_team' => 'topics#assign_team', as: :assign_team
    get 'topics/unassign_team' => 'topics#unassign_team', as: :unassign_team
    post 'topics/:topic_id/split/:post_id' => 'topics#split_topic', as: :split_topic
    get 'shortcuts' => 'topics#shortcuts', as: :shortcuts
    get 'empty_trash' => 'topics#empty_trash', as: :empty_trash

    # SearchController Routes
    get 'search/topic_search' => 'search#topic_search', as: :topic_search

    # Settings Routes
    get 'settings' => 'settings#index', as: :settings
    get 'settings/preview' => 'settings#preview', as: :preview
    put 'update_settings/' => 'settings#update_settings', as: :update_settings
    get 'settings/general' => 'settings#general', as: :general_settings
    get 'settings/design' => 'settings#design', as: :design_settings
    get 'settings/theme' => 'settings#theme', as: :theme_settings
    get 'settings/widget' => 'settings#widget', as: :widget_settings
    get 'settings/i18n' => 'settings#i18n', as: :i18n_settings
    get 'settings/email' => 'settings#email', as: :email_settings
    get 'settings/integration' => 'settings#integration', as: :integration_settings
    put 'settings/general' => 'settings#update_general', as: :update_general_settings
    put 'settings/design' => 'settings#update_design', as: :update_design_settings
    put 'settings/theme' => 'settings#update_theme', as: :update_theme_settings
    put 'settings/widget' => 'settings#update_widget', as: :update_widget_settings
    put 'settings/i18n' => 'settings#update_i18n', as: :update_i18n_settings
    put 'settings/email' => 'settings#update_email', as: :update_email_settings
    put 'settings/integration' => 'settings#update_integration', as: :update_integration_settings
    get 'settings/profile' => 'settings#profile', as: :profile_settings
    get 'settings/trash' => 'settings#trash', as: :trash_settings

    # Misc Routes
    post 'shared/update_order' => 'shared#update_order', as: :update_order
    get 'cancel_edit_post/:id/' => 'posts#cancel', as: :cancel_edit_post
    get 'users/invite' => 'users#invite', as: :invite
    put 'users/invite_users' => 'users#invite_users', as: :invite_users

    # Export Routes
    get 'backups' => 'backups#index', as: :backups
    get 'backups/export' => "backups/export", as: :export_backup
    get  'backups/download' => "backups/download", as: :download
    delete 'backups/:id(.:format)', :to => 'backups#destroy', as: :delete_backup

    # Import Routes
    resources :imports, only: [:index, :show]
    post 'imports/restore' => "importz/restore", as: :import_restore

    post 'posts/users' => 'posts#search', as: :user_search
    get  'posts/new_user' => 'posts#new_user', as: :new_user
    post  'posts/new_user' => 'posts#change_owner_new_user'

    get 'internal_docs/search' => 'internal_categories#search', as: :internal_docs_search

    patch 'categories/reorganize' => 'categories#reorganize', as: :reorganize
    resources :categories do
      resources :docs, except: [:index, :show]
    end


    resources :internal_categories, only: [:index, :show] do
      resources :internal_docs, only: :show
    end

    resources :docs, except: [:index, :show]
    get 'agent_assistant' => 'agent_assistant#index', as: :agent_assist

    resources :images, only: [:create, :destroy]
    resources :forums# , except: [:index, :show]
    resources :users
    post 'users/:id/scrub' => 'users#scrub', as: :scrub_user
    scope 'settings' do
      resources :api_keys, except: [:show, :edit, :update]
      resources :groups
      resources :tags
    end
    resources :topics, except: [:delete, :edit] do
      resources :posts
    end
    resources :posts
    
    get '/posts/:id/raw' => 'posts#raw', as: :post_raw
    get '/dashboard' => 'dashboard#index', as: :dashboard
    get '/reports/team' => 'reports#team', as: :team_reports
    get '/reports/groups' => 'reports#groups', as: :group_reports
    get '/reports' => 'reports#index', as: :reports

    get '/dashboard/blank' => 'dashboard#blank', as: :blank_dashboard

    root to: 'dashboard#index'
  end

  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine => '/api/v1/api_doc'

  # Receive email from Griddler
  mount_griddler

  # Mount attachinary
  mount Attachinary::Engine => "/attachinary"

end

app/models/forum.rb
# == Schema Information
#
# Table name: forums
#
#  id                 :integer          not null, primary key
#  name               :string
#  description        :text
#  topics_count       :integer          default(0), not null
#  last_post_date     :datetime
#  last_post_id       :integer
#  private            :boolean          default(FALSE)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  allow_topic_voting :boolean          default(FALSE)
#  allow_post_voting  :boolean          default(FALSE)
#  layout             :string           default("table")
#

class Forum < ActiveRecord::Base

  include SentenceCase

  has_many :topics, dependent: :delete_all
  has_many :posts, through: :topics

  scope :alpha, -> { order('name ASC') }

  # provided both public and private instead of one method, for code readability
  scope :isprivate, -> { where(private: true)}
  scope :ispublic, -> { where(private: false)}
  scope :for_docs, -> { where(name: 'Doc comments') }

  validates :name, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 1000 }

  def total_posts
    self.posts.count
  end

  def to_param
    "#{id}-#{name.parameterize}" unless name.nil?
  end

end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper

  def ticket_page_title
    concat j ticket_status_label
    concat j new_ticket_button
    concat j ticket_nav_dropdown
  end

  def user_page_title

  end

  def started_by(topic)
    return "Missing User" if topic.user.nil?
    user_name = topic.user.name
    link_to t(:started_by, username: user_name.titleize, default: "Started by #{user_name}"), admin_user_path(topic.user.id), remote: true
  end

  def topic_added_from
    content_tag :small, class: 'less-important hidden-xs' do
      concat t(:topic_added_from, kind: @topic.kind, channel: @topic.channel)
      concat ": #{link_to(@doc.title, edit_admin_category_doc_path(@doc.category_id, @doc.id, lang: I18n.locale))}".html_safe if @doc.present?
    end
  end

  def topic_anonymous_link
    content_tag :div, class: 'pull-right' do
      content_tag :small, class: 'less-important anonymous-link' do
        link_to topic_path(id: @topic.hashid), target: 'blank' do
          content_tag :i, nil, class: 'fas fa-link' 
        end
      end 
    end if AppSettings['settings.anonymous_access'] == "1"
  end

  def ticket_status_label
    content_tag :span, class: "label #{status_class(@status)}", style: 'text-transform: uppercase' do
      status_label(@status)
    end
  end

  def new_ticket_button
    content_tag :span, class: 'hidden-xs pull-right' do
      link_to t(:open_new_discussion, default: 'Open Discussion'), new_admin_topic_path, remote: true, class: 'btn btn-primary' if tickets?
    end
  end

  def ticket_nav_dropdown
    render partial: 'admin/topics/ticket_nav_dropdown'
  end

  def user_priority(user)
    return unless user.priority?
    content_tag :span, class: 'label label-tag', style: 'text-transform: uppercase' do
      user.priority
    end
  end

  def agents_for_select
    User.agents.all.map { |user| [user.name, user.id] }
  end

  def channels_collection
    [
      [t('activerecord.attributes.user.email'), 'email'],
      [t('activerecord.attributes.user.home_phone'), 'phone'],
      [t(:channel_in_person, default: 'In Person'), 'person']
    ]
  end

  def statuses_collection
    statuses = []
    ['new','open','pending','closed'].each do |s|
      statuses << [t(s.to_sym), s]
    end
    statuses
  end

  def ticket_types_collection
    [
      [t('customer_conversation', default: "Customer Conversation"), 'ticket'],
      [t('internal_ticket', default: "Internal Ticket"), 'internal']
    ]
  end

  def ticket_priority_collection
    Topic.priorities.keys.map { |priority| [t("#{priority}_priority"), priority] }
  end

  def ticket_tag_collection
    ActsAsTaggableOn::Tagging.all.where(context: "tags", taggable_type: 'Topic').includes(:tag).map{|tagging| tagging.tag.name }.uniq.sort
  end

  # id of opening or first post in the topic
  def first_post_id(topic)
    first_post = topic.posts.order(created_at: :asc).first
    first_post.present? ? first_post.id : nil
  end

  # show topic tag form
  def topic_tag_form
    return nil if ticket_tag_collection.blank?
    simple_form_for @topic, url: admin_update_topic_tags_path(id: @topic.id, status: params[:status]), remote: true, html: { class: 'form-inline tag-form' } do |f|
      content_tag :div, class: 'row' do
        content_tag :div, class: 'col-md-8' do
          f.input :tag_list, collection: ticket_tag_collection, 
            as: :select, include_blank: false, label: false,
            input_html: { multiple: true, class: '', placeholder: 'click to add tags...' },
            # wrapper_html: { style: 'width: 0' }, 
            data: { 'none-selected-text': t('tag_with', default: 'Tag Ticket'), 'live-search': false, 'width': '150px', dropdownAlignRight: false },
            style: 'width: 280px;'
            
        end
      end
    end
  end

  # tag button label
  def tags_button_label
    if @topic.tag_list.count > 0
      pluralize @topic.tag_list.count, "Tag"
    else
      t(:tag_with, default: "Tag Ticket")
    end
  end

end

app/helpers/topics_helper.rb
# == Schema Information
#
# Table name: topics
#
#  id               :integer          not null, primary key
#  forum_id         :integer
#  user_id          :integer
#  user_name        :string
#  name             :string
#  posts_count      :integer          default(0), not null
#  waiting_on       :string           default("admin"), not null
#  last_post_date   :datetime
#  closed_date      :datetime
#  last_post_id     :integer
#  current_status   :string           default("new"), not null
#  private          :boolean          default(FALSE)
#  assigned_user_id :integer
#  cheatsheet       :boolean          default(FALSE)
#  points           :integer          default(0)
#  post_cache       :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  locale           :string
#  doc_id           :integer          default(0)
#  channel          :string           default("email")
#  kind             :string           default("ticket")
#  priority         :integer          default(1)
#

module TopicsHelper

  def badge_for_status(status)
    content_tag(:span, status_label(status), class: "hidden-xs pull-right status-label label #{status_class(status)}")
  end

  def badge_for_private
    content_tag(:span, t(:private, default: 'PRIVATE'), class: 'hidden-xs pull-right status-label label label-private')
  end

  def badge_for_public
    content_tag(:span, t(:public, default: 'PUBLIC'), class: 'hidden-xs pull-right status-label label label-public')
  end

  def control_for_status(status)
    content_tag(:span, "#{status_label(status)} <span class='caret'></span> ".html_safe, class: "change-status btn status-label-button label #{status_class(status)}")
  end

  def control_for_privacy(private_flag)
    str = private_flag ? t(:private, default: 'PRIVATE') : t(:public, default: 'PUBLIC')
    content_tag(:span, "#{str} <span class='caret'></span> ".html_safe, class: 'btn status-label-button change-privacy privacy-label label label-info')
  end

  def status_label(status)
    case status
      when 'new'
        t(:new, default: 'new')
      when 'open'
        t(:open, default: 'open')
      when 'active'
        t(:active, default: 'active')
      when 'assigned'
        t(:mine, default: 'mine')
      when 'closed'
        t(:closed, default: 'resolved')
      when 'pending'
        t(:pending, default: 'pending')
      when 'spam'
        t(:spam, default: 'spam')
      when 'trash'
        t(:trash, default: 'trash')
    end
  end

  def status_class(status)
    case status
      when 'new'
        'label-info'
      when 'open'
        'label-success'
      when 'closed'
        'label-default'
      when 'pending'
        'label-warning'
      when 'spam'
        'label-danger'
      when 'trash'
        'label-danger'
    end
  end

  # Lookup the user set color, if it exists
  def badge_color_from_tag(tag_name)
    tagging = ActsAsTaggableOn::Tag.where('lower(name) = ?', tag_name.downcase).first
    tagging.present? && tagging.color.present? ? 'background-color: ' + tagging.color : ''
  end

  def badge_color_from_topic(topic)
    return '' if topic.team_list.blank?

    tagging = ActsAsTaggableOn::Tag.where('lower(name) = ?', topic.team_list.first.downcase)
    return badge_color_from_tag(tagging.first.name) unless tagging.nil?
  end

  def all_teams
    ActsAsTaggableOn::Tagging.all.where(context: "teams").includes(:tag).where("context = 'teams' and tags.show_on_helpcenter = ?", 'true').references(:tags).map{|tagging| tagging.tag.name.capitalize }.uniq
  end

  def color_sample(tag_name)
    content_tag(:div, '', style: badge_color_from_tag(tag_name), class: 'color-sample label-' + tag_name.first.downcase) + content_tag(:div, tag_name.try(:titleize))
  end

  def extension_whitelist
    return "" unless AppSettings['settings.extension_whitelist'].present?
    
    "'#{[AppSettings['settings.extension_whitelist'].split(',').map(&:strip)].join("', '")}'"
  end

  def extension_blacklist
    return "" unless AppSettings['settings.extension_blacklist'].present?

    "'#{[AppSettings['settings.extension_blacklist'].split(',').map(&:strip)].join("', '")}'".html_safe
  end

end

app/views/admin/topics/_nav_item.html.erb
<li class="text-left nav-item ticket-nav-<%= status %> <%= 'more-important nav-active' if @status == status %>">
  <%= content_tag :div, count, class: 'pull-right' %>
  <%= link_to label, admin_topics_path(:status => status), :remote => true,
  class: "pipeline-#{status}" %>
</li>

app/views/admin/topics/_post.html.erb
<!-- Admin post partial -->
<div id="post-<%= post.id %>" class="media post-container disallow-post-voting <%= "kind-#{post.kind}" %><%= " inactive" unless post.active? %> overflow-visible" <%= 'style="display:none;"' if post.kind == 'note' %>>
	<%= content_tag :div, avatar_image(post.user, size=40), class: 'pull-left' if post.kind != 'first' %>
	<div class="media-body media-right overflow-visible no-side-pad">
		<span class="hidden-sm hidden-md hidden-lg"><%= last_active_time(post.created_at) %><br/></span>
		<span id="row-<%= post.id %>"  class="post-menu post-menu-<%= post.id %> btn-group">
			<%= post_message(post,true) %>
			<ul class="dropdown-menu dropdown-menu-left" role="menu">
				<li><%= link_to t('edit', default: "Edit"), edit_admin_post_path(post), remote: true %></li>
				<li><%= link_to t('convert_content', default: 'Turn post into content'), new_admin_doc_path(post_id: post.id, lang: I18n.locale) %></li>
        <li><%= link_to t('new_discussion', default: 'Create new discussion from this'), admin_split_topic_path(topic_id: post.topic_id, post_id: post.id), method: :post, remote: true %></li>
        <li><%= link_to t('change_owner', default: 'Change author'), '#', data: { toggle: "modal", target: "#change-user-modal-#{post.id}" } %></li>
        <%= content_tag :li, link_to(t('Show Raw Email', default: 'Raw Email'), admin_post_raw_path(post), target: 'blank') if post.raw_email.present? %>
			</ul>
		</span>

		<span class="last-active posted-at less-important pull-right">
			<span class="hidden-xs">
			<%= last_active_time(post.created_at) %>
			</span>
		</span>
		<%= content_tag :div, post.cc.present? ? "cc: #{post.cc}" : "", class: 'post-cc post-cc-style' %>
		<%= content_tag :div, post.bcc.present? ? "bcc: #{post.bcc}" : "", class: 'post-bcc post-cc-style' %>
		<div id="post-body-<%= post.id %>" class="post-body less-important text-left">
			<%= post.html_formatted_body -%>
      		<%= render partial: 'posts/thumbnail', locals: { :model_name => post } if cloudinary_enabled? %>
			<%= render partial: 'posts/attachment', locals: { :model_name => post } %>
		</div>

	</div>
</div>

<div id="change-user-modal-<%= post.id %>" class="modal fade change-user-modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title"><%= t('change_owner', default: 'Change author') %></h4>
			</div>

			<div class="modal-body row">
				<div class="col-md-12">
					<%= bootstrap_form_tag url: admin_user_search_path, method: 'post', remote: true, html: { class: 'search_form' } do |f| -%>
						<%= hidden_field_tag 'post_id', post.id %>
						<%= f.text_field :user_search, skip_label: true, placeholder: 'Type users name or email', autocomplete: :off, onkeyup: "search_user(#{post.id})" -%>
					<% end -%>
					<div class="search-results">
					</div>
				</div>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/admin/topics/_topic_options.html.erb
<script>
  Helpy.topicID = <%= @topic.id %>;
</script>
<div class="pull-right">
  <span class="btn-group left-col-dropdown">
    <%= link_to content_tag(:span, '', class: 'fas fa-ellipsis-v ticket-ellipsis btn'), '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' }%>
    <ul class="dropdown-menu dropdown-menu-right" role="menu">
      <li><%= link_to t('change_owner', default: 'Change author'), '#', data: { toggle: "modal", target: "#change-user-modal-#{first_post_id(@topic)}" } if @topic.posts.present? %></li>
      <hr/>
      <% if @topic.user.present? %>
      <li class="dropdown-header"><%= @topic.user.name %></li>
      <li><%= link_to t(:tickets, default: 'Tickets'), remote: true %></li>
      <li><%= link_to t(:open_new_discussion, default: 'Open Discussion'), new_admin_topic_path(user_id: @topic.user.id), remote: true, class: '' if tickets? %></li>
      <li><%= link_to t(:edit_user, default: 'Edit User'), edit_admin_user_path(@topic.user), remote: false if @topic.user.can_be_edited? current_user %></li>
      <% end %>
    </ul>
  </span>
</div>
<span class="btn-group left-col-dropdown">
  <button class="status dropdown-toggle ticket-control" data-toggle="dropdown" aria-expanded="false">
    <%= control_for_status(@topic.current_status) %>
  </button>
  <ul class="dropdown-menu ticket-controls" role="menu">
    <li><%= link_to t(:mark_closed, default: 'Mark Closed'), admin_update_topic_path(topic_ids: { "":@topic.id }, change_status: 'closed', status: @status), :remote => true, class: 'key-sr' unless @topic.current_status == "closed" %></li>
    <li><%= link_to t(:reopen, default: 'Reopen'), admin_update_topic_path(topic_ids: { "":@topic.id }, change_status: 'reopen', status: @status), :remote => true, class: 'key-so' unless @topic.current_status == "open" %></li>
    <li><%= link_to t(:mark_new, default: 'Mark New'), admin_update_topic_path(topic_ids: { "":@topic.id }, change_status: 'new', status: @status), :remote => true, class: 'key-sn' unless @topic.current_status == "new" %></li>
    <li><%= link_to t(:mark_spam, default: 'Mark Spam'), admin_update_topic_path(topic_ids: { "":@topic.id }, change_status: 'spam', status: @status), :remote => true, class: 'key-ss' unless @topic.current_status == "spam" %></li>
    <li><%= link_to t(:trash, default: 'Trash'), admin_update_topic_path(topic_ids: { "":@topic.id }, change_status: 'trash', status: @status), :remote => true, class: 'key-st' unless @topic.current_status == "trash" %></li>
  </ul>
</span>

<% if forums? %>
  <span class="status privacy btn-group left-col-dropdown">
    <button class="privacy-toggle dropdown-toggle ticket-control" data-toggle="dropdown" aria-expanded="false">
      <%= control_for_privacy(@topic.private?) %>
    </button>
    <ul class="dropdown-menu ticket-controls" role="menu">
      <% Forum.where(private: false).alpha.each do |forum| %>
      <li><%= link_to "#{t(:move_to, default: "Move")}: #{forum.name}", admin_toggle_privacy_path(topic_ids: { "":@topic.id }, private: 'false', forum_id: forum.id, status: @status), :remote => true %></li>
      <% end %>
      <li><%= link_to "#{t(:mark_as, default: "Mark")}: Private", admin_toggle_privacy_path(topic_ids: { "":@topic.id }, private: 'true', forum_id: 1, status: @status), :remote => true %></li>
    </ul>
  </span>
<% end %>

<% unless @topic.current_status == "closed" %>
  <span class="status btn-group left-col-dropdown">
    <button class="dropdown-toggle ticket-control" data-toggle="dropdown" aria-expanded="false">
      <%= content_tag :span, class: 'btn status-label-button label label-warning assign-to' do %>
        <%= @topic.assigned_user.try(:name).try(:upcase) || t(:unassigned, default: 'UNASSIGNED') %>
        <%= content_tag(:i, nil, class: 'caret') + ' ' %>
      <% end %>
    </button>
    <ul class="dropdown-menu ticket-controls" role="menu">
      <li><%= link_to "#{current_user.name.titleize}", admin_assign_agent_path(topic_ids: { "":@topic.id }, assigned_user_id: current_user.id, status: @status), :remote => true unless @topic.current_status == "closed" %></li>
      <li role="separator" class="divider"></li>
      <% (@admins-[current_user]).each do |admin| %>
      <li><%= link_to "#{admin.name.titleize} (#{admin.active_assigned_count})", admin_assign_agent_path(topic_ids: { "":@topic.id }, assigned_user_id: admin.id, status: @status), :remote => true unless @topic.current_status == "closed" %></li>
      <% end %>
      <hr/>
      <li><%= link_to t(:unassign_agent, default: "Unassign Agent"), admin_unassign_agent_path(topic_ids: { "":@topic.id }, assigned_user_id: '', status: @status), :remote => true %></li>
    </ul>
  </span>

  <span class="status btn-group left-col-dropdown">
    <button class="dropdown-toggle ticket-control" data-toggle="dropdown" aria-expanded="false">
      <%= content_tag(:span, style: badge_color_from_topic(@topic), class: "btn status-label-button group-to label label-#{@topic.team_list.present? ? @topic.team_list.first.first.downcase : 'default'}") do %>
        <%= @topic.team_list.first.try(:upcase) || t(:no_team_assigned, default: 'Assign to group') %>
        <%= content_tag(:i, nil, class: 'caret') + ' ' %>
      <% end %>
    </button>
    <ul class="dropdown-menu ticket-controls team-list" role="menu">
      <% @all_teams.to_a.each do |team| %>
        <li class='team-item'>
          <% unless @topic.current_status == "closed" %>
            <%= link_to(color_sample(team), admin_assign_team_path(topic_ids: { "":@topic.id }, assign_team: team, status: @status), :remote => true) %>
          <% end %>
        </li>
      <% end %>
      <hr/>
      <li><%= link_to t(:unassign_from_team, default: "Unassign from group"), admin_unassign_team_path(topic_ids: { "":@topic.id }, team: '', status: @status), :remote => true unless @topic.current_status == "closed" %></li>

    </ul>
  </span>

  <span class="status btn-group left-col-dropdown">
    <button class="dropdown-toggle ticket-control tag-toggle" aria-expanded="false">
      <%= content_tag :span, class: 'btn label-light status-label-button label' do %>
        <%= tags_button_label %>
        <%= content_tag(:i, nil, class: 'caret') + ' ' %>
      <% end %>
    </button>
    <ul class="dropdown-menu ticket-controls" role="menu">
      <li class="dropdown mega-dropdown">
        <span class="topic-tag-form">
          <style>
            .selectize-input {
              border: 1px;
              font-weight: normal;
              text-transform: uppercase;
            }
        
            .selectize-input .item {
              background-color: #ddd;
              color: #666;
            }

            .selectize-control.form-control.select.optional.multi {
              width: 280px;
            }
          </style>
          <%= topic_tag_form %>
        </span>
      </li>
    </ul>
  </span>
<% end %>